spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/nebula
    username: nebula
    password: nebula
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  rabbitmq:
    host: rabbitmq
    port: 5672

worker:
  work-dir: /tmp/worker
  process-timeout-seconds: 300 # default timeout for commands
  clone-timeout-seconds: 120
  retry:
    initial-delay-ms: 2000
    max-delay-ms: 60000
    multiplier: 2.0

logging:
  level:
    root: INFO
